# A config file for OrcaSong with a list of all configuration options.
# More info about the .toml format at https://github.com/toml-lang/toml

### All available options with some dummy values
# --o = '/home/woody/capn/mppi033h/orcasong_output'
# --chunksize = 32
# --complib = 'zlib'
# --complevel = '1'
# --n_bins = '11,13,18,60'
# --det_geo = 'Orca_115l_23m_h_9m_v'
# --do2d = false
# --do2d_plots = false
# --do2d_plots_n = 10
# --do3d = false
# --do4d = true
# --do4d_mode = 'time'
# --timecut_mode = 'trigger_cluster'
# --timecut_timespan = 'tight_1'
# --do_mc_hits = false
# --data_cut_triggered = false
# --data_cut_e_low = 3
# --data_cut_e_high = 100
# --data_cut_throw_away = 0.00
# --prod_ident = 1


####----- Configuration for ORCA 115l -----####

###--- 3-100GeV ---###

## XYZ-T

output_dirpath = '/home/woody/capn/mppi033h'
chunksize = 32
complib = 'zlib'
complevel = 1
n_bins = [11,13,18,100]
det_geo = 'Orca_115l_23m_h_9m_v'
do2d = false
do2d_plots = false
do2d_plots_n = 10
do3d = false
do4d = true
do4d_mode = 'time'
timecut_mode = 'trigger_cluster'
timecut_timespan = 'tight-0'
do_mc_hits = false
data_cut_triggered = false
data_cut_e_low = 'None'
data_cut_e_high = 'None'
data_cut_throw_away = 'None'
prod_ident = 3 # for neutrinos: 1: 3-100 GeV prod, 2: 1-5 GeV prod ; mupage: 3 ; random_noise: 4
flush_freq = 1000